// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID        string `json:"id"`
	AuthorID  string `json:"authorID"`
	Content   string `json:"content"`
	Timestamp string `json:"timestamp"`
}

type Query struct {
}
